model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_GC
  params:
    seq_length: 24
    feature_size: 20
    n_layer_enc: 4
    n_layer_dec: 4
    d_model: 512  # 4 X 16
    timesteps: 1000
    sampling_timesteps: 1000
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.1
    resid_pd: 0.1
    kernel_size: 5
    padding_size: 2
    reg_weight: 0.2
    
    
regularizer:
  prox_lambda: 5
  ridge_lambda: 1.0e-3

solver:
  base_lr: 1.0e-5
  multiple_prox_step: 100
  early_stop_patience: 100
  weight_decay: 1.0e-5
  max_epochs: 2000
  results_folder: ./my_exp/
  gradient_accumulate_every: 2
  save_cycle: 500  # max_epochs // 10
  ema:
    decay: 0.9
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 50
      min_lr: 1.0e-7
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 5.0e-4
      warmup: 50 
      verbose: False

